[build]
  publish = "."

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/admin-dashboard"
  to = "/admin-dashboard.html"
  status = 200

[[redirects]]
  from = "/associate-portal"
  to = "/associate-portal.html"
  status = 200

[[redirects]]
  from = "/cv-creator"
  to = "/cv-creator.html"
  status = 200

# Contact form handling
[[forms]]
  name = "contact"

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
